In [1]:
import pandas as pd
df_video = pd.read_csv("D:\\youtube_trending_analysis\\data_merge\\df_video_full.csv")
df_comments = pd.read_csv("D:\\youtube_trending_analysis\\data_merge\\df_comments_full.csv")

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_7172\3223631746.py:2: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_video = pd.read_csv("D:\\youtube_trending_analysis\\data_merge\\df_video_full.csv")

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
df_video.head()

,video_id,time_id,views,likes,comment_count,crawl_timestamp,is_trending,title,channel_id,thumbnail,duration,tags,category_id,keyword_id,topic_id,publish_time,channel_title,country,subscriber_count,video_count,total_views,topic_name,keyword,year,month,day,hour,weekday
0,JJXKkfUYM9c,2026031012,95250,2781,2272,2026-03-10 12:40:34.402602,NaN,Honor X9d Review - Masakit man pero Kailangan !,UC7iCSSpCsNw34E1o0DwgJBA,https://i.ytimg.com/vi/JJXKkfUYM9c/default.jpg,1230,NaN,28,61,7,2026-01-23T10:21:18Z,Gadget Tech Tips,PH,156000.0,1210.0,3.478252e+07,technology,tech review,2026,3,10,12,1
1,JXZCpQsY0e4,2026031012,54979,4922,1660,2026-03-10 12:40:34.402602,NaN,"ReviewTechUSA Is Back (I Made A Mistake, Here&...",UCOuKecIw7ObKsLCMimUbbMA,https://i.ytimg.com/vi/JXZCpQsY0e4/default.jpg,389,"richard masucci,rich masucci,reviewtechusa mel...",22,61,7,2025-12-18T21:50:27Z,ReviewTechUSA2,Unknown,92600.0,1298.0,2.017776e+07,technology,tech review,2026,3,10,12,1
2,mkcgVN90zl0,2026031012,11565022,556461,5344,2026-03-10 12:40:34.402602,NaN,This Gadget BRICKS Your Phone!,UCMiJRAwDNSNzuYeN2uWa0pA,https://i.ytimg.com/vi/mkcgVN90zl0/default.jpg,48,NaN,28,61,7,2025-02-21T14:57:07Z,Mrwhosetheboss,GB,22300000.0,1886.0,8.356295e+09,technology,tech review,2026,3,10,12,1
3,ObqHKHoSE5Y,2026031012,4042883,123695,9221,2026-03-10 12:40:34.402602,NaN,Samsung S26 Ultra Hands on - What&#39;s ACTUAL...,UCMiJRAwDNSNzuYeN2uWa0pA,https://i.ytimg.com/vi/ObqHKHoSE5Y/default.jpg,857,"samsung,galaxy,s26,s26 ultra,s26 ultra review,...",28,61,7,2026-02-25T18:00:00Z,Mrwhosetheboss,GB,22300000.0,1886.0,8.356295e+09,technology,tech review,2026,3,10,12,1
4,RvP-uVNwnXo,2026031012,3844230,90816,2448,2026-03-10 12:40:34.402602,NaN,Dope Tech: STILL so good!,UCBJycsmduvYEL83R_U4JriQ,https://i.ytimg.com/vi/RvP-uVNwnXo/default.jpg,1014,"Dope Tech,dope tech,MKBHD,MX Master 4,Devialet...",28,61,7,2025-11-21T19:00:50Z,Marques Brownlee,US,20800000.0,1805.0,5.299716e+09,technology,tech review,2026,3,10,12,1

In [4]:
df_video.isnull().sum()

video_id                0
time_id                 0
views                   0
likes                   0
comment_count           0
crawl_timestamp         0
is_trending         36164
title                   0
channel_id              0
thumbnail               0
duration                0
tags                28423
category_id             0
keyword_id              0
topic_id                0
publish_time            0
channel_title          16
country                16
subscriber_count       16
video_count            16
total_views            16
topic_name              0
keyword                 0
year                    0
month                   0
day                     0
hour                    0
weekday                 0
dtype: int64

In [5]:
df_video['tags'] = df_video['tags'].fillna("Unknown")

In [6]:
df_video.duplicated().sum()

0

In [7]:
df_video = df_video.dropna(subset=['channel_title', 'country', 'subscriber_count', 'video_count', 'total_views'])

In [8]:
df_video.isnull().sum()

video_id                0
time_id                 0
views                   0
likes                   0
comment_count           0
crawl_timestamp         0
is_trending         36164
title                   0
channel_id              0
thumbnail               0
duration                0
tags                    0
category_id             0
keyword_id              0
topic_id                0
publish_time            0
channel_title           0
country                 0
subscriber_count        0
video_count             0
total_views             0
topic_name              0
keyword                 0
year                    0
month                   0
day                     0
hour                    0
weekday                 0
dtype: int64

In [9]:
df_video

,video_id,time_id,views,likes,comment_count,crawl_timestamp,is_trending,title,channel_id,thumbnail,duration,tags,category_id,keyword_id,topic_id,publish_time,channel_title,country,subscriber_count,video_count,total_views,topic_name,keyword,year,month,day,hour,weekday
0,JJXKkfUYM9c,2026031012,95250,2781,2272,2026-03-10 12:40:34.402602,NaN,Honor X9d Review - Masakit man pero Kailangan !,UC7iCSSpCsNw34E1o0DwgJBA,https://i.ytimg.com/vi/JJXKkfUYM9c/default.jpg,1230,Unknown,28,61,7,2026-01-23T10:21:18Z,Gadget Tech Tips,PH,156000.0,1210.0,3.478252e+07,technology,tech review,2026,3,10,12,1
1,JXZCpQsY0e4,2026031012,54979,4922,1660,2026-03-10 12:40:34.402602,NaN,"ReviewTechUSA Is Back (I Made A Mistake, Here&...",UCOuKecIw7ObKsLCMimUbbMA,https://i.ytimg.com/vi/JXZCpQsY0e4/default.jpg,389,"richard masucci,rich masucci,reviewtechusa mel...",22,61,7,2025-12-18T21:50:27Z,ReviewTechUSA2,Unknown,92600.0,1298.0,2.017776e+07,technology,tech review,2026,3,10,12,1
2,mkcgVN90zl0,2026031012,11565022,556461,5344,2026-03-10 12:40:34.402602,NaN,This Gadget BRICKS Your Phone!,UCMiJRAwDNSNzuYeN2uWa0pA,https://i.ytimg.com/vi/mkcgVN90zl0/default.jpg,48,Unknown,28,61,7,2025-02-21T14:57:07Z,Mrwhosetheboss,GB,22300000.0,1886.0,8.356295e+09,technology,tech review,2026,3,10,12,1
3,ObqHKHoSE5Y,2026031012,4042883,123695,9221,2026-03-10 12:40:34.402602,NaN,Samsung S26 Ultra Hands on - What&#39;s ACTUAL...,UCMiJRAwDNSNzuYeN2uWa0pA,https://i.ytimg.com/vi/ObqHKHoSE5Y/default.jpg,857,"samsung,galaxy,s26,s26 ultra,s26 ultra review,...",28,61,7,2026-02-25T18:00:00Z,Mrwhosetheboss,GB,22300000.0,1886.0,8.356295e+09,technology,tech review,2026,3,10,12,1
4,RvP-uVNwnXo,2026031012,3844230,90816,2448,2026-03-10 12:40:34.402602,NaN,Dope Tech: STILL so good!,UCBJycsmduvYEL83R_U4JriQ,https://i.ytimg.com/vi/RvP-uVNwnXo/default.jpg,1014,"Dope Tech,dope tech,MKBHD,MX Master 4,Devialet...",28,61,7,2025-11-21T19:00:50Z,Marques Brownlee,US,20800000.0,1805.0,5.299716e+09,technology,tech review,2026,3,10,12,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74978,tjdAvErwwEE,2026050914,611392,9604,423,2026-05-09 14:36:18.765630,True,Lisandro Cuxi x Loony Johnson - SIKI SIKI (Remix),UCWFtq-yPoyeuFP3eaDcQHUQ,https://i.ytimg.com/vi/tjdAvErwwEE/default.jpg,188,Unknown,10,97,10,2026-04-15T16:00:39Z,Lisandro Cuxi,PT,330000.0,16.0,1.146420e+08,music,official music video,2026,5,9,14,5
74979,PA2aWF37Ljk,2026050914,9506434,218714,30856,2026-05-09 14:36:18.765630,True,TEDDY AFRO - ጀምበር - Jember | Track 18 (Offici...,UCydlocDyvRtFmMffKytKqgQ,https://i.ytimg.com/vi/PA2aWF37Ljk/default.jpg,394,Unknown,10,97,10,2026-04-16T11:00:24Z,Teddy Afro,US,2030000.0,102.0,5.139610e+08,music,official music video,2026,5,9,14,5
74980,2bHMD_fUVpo,2026050914,1625330,23457,848,2026-05-09 14:36:18.765630,True,Calema - Chuva De Amor,UC4Sx0tMqY7Z6VZKL8Z76tog,https://i.ytimg.com/vi/2bHMD_fUVpo/default.jpg,231,"calema,amar pela metade,calema amar pela metad...",10,97,10,2026-04-04T11:00:06Z,CalemaVEVO,Unknown,721.0,23.0,1.156245e+08,music,official music video,2026,5,9,14,5
74981,wHPX1XWexLg,2026050914,1161988,68414,7878,2026-05-09 14:36:18.765630,True,J'ai RELANCÉ Brawl Stars après 1 an..,UCiFyJ_EBmF2XJuR9buWE_3A,https://i.ytimg.com/vi/wHPX1XWexLg/default.jpg,1289,"unchained,unchained_off,unchained fortnite,for...",20,57,6,2026-04-27T15:04:01Z,Unchained_Off,FR,6970000.0,1704.0,3.766049e+09,gaming,gaming highlights,2026,5,9,14,5
74982,oFxjmRTggv0,2026050914,1116332,78114,3217,2026-05-09 14:36:18.765630,True,Crimson Desert - LE PLUS MAUVAIS OPEN WORLD (d...,UC4peNo-31r7fhQZgu0_JRIA,https://i.ytimg.com/vi/oFxjmRTggv0/default.jpg,2041,Unknown,20,57,6,2026-04-10T15:00:34Z,Sheshounet,FR,1240000.0,273.0,2.689176e+08,gaming,gaming highlights,2026,5,9,14,5

In [13]:
df_comments

,comment_id,video_id,time_id,comment_text,like_count,title,topic_id,topic_name
0,UgxIPKOQXWACvLf4fYF4AaABAg,JJXKkfUYM9c,2026012413,sana ako mabunot need ko tlga cp kasi nag haha...,10,Honor X9d Review - Masakit man pero Kailangan !,7.0,technology
1,UgwOuKkXxF_M4l_PvZB4AaABAg,JJXKkfUYM9c,2026031004,yan nlang bilhin ko,0,Honor X9d Review - Masakit man pero Kailangan !,7.0,technology
2,UgzqCZ7H73rJ0rAAOAt4AaABAg,JJXKkfUYM9c,2026030909,pang regalo lng lods sa anak ko salamat,0,Honor X9d Review - Masakit man pero Kailangan !,7.0,technology
3,UgysoXXsEaAiveRJ57R4AaABAg,JJXKkfUYM9c,2026030806,watching gamit honor x9d matibay nga po yan,0,Honor X9d Review - Masakit man pero Kailangan !,7.0,technology
4,UgxqqhHLeLNn_bYMqBJ4AaABAg,JJXKkfUYM9c,2026030800,honox9d din unit ko pero dko susubukan yan,0,Honor X9d Review - Masakit man pero Kailangan !,7.0,technology
...,...,...,...,...,...,...,...,...
1361041,UgwYgk3ZjNo2DzlmCzR4AaABAg,oFxjmRTggv0,2026042322,merci je n osez pas franchir le pas sur ce jeu...,0,Crimson Desert - LE PLUS MAUVAIS OPEN WORLD (d...,6.0,gaming
1361042,UgyA9js-xW7dicQNvIR4AaABAg,oFxjmRTggv0,2026042320,petit commentaire pour le soutiens merci pour ...,0,Crimson Desert - LE PLUS MAUVAIS OPEN WORLD (d...,6.0,gaming
1361043,Ugx6bv4WkwxRfQQ1NDd4AaABAg,oFxjmRTggv0,2026042319,merci pour cette vidéo ! excellent ! je n ai q...,0,Crimson Desert - LE PLUS MAUVAIS OPEN WORLD (d...,6.0,gaming
1361044,Ugw5UM9v4oX4UD4EQJV4AaABAg,oFxjmRTggv0,2026042318,il a coulé avec le code,0,Crimson Desert - LE PLUS MAUVAIS OPEN WORLD (d...,6.0,gaming
1361045,UgzfndCRElQTVSKFUd14AaABAg,oFxjmRTggv0,2026042316,ce succès de malade!,0,Crimson Desert - LE PLUS MAUVAIS OPEN WORLD (d...,6.0,gaming

In [11]:
import re
import html

def clean_text(text):
    text = str(text)
    text = html.unescape(text)           # Decode HTML
    text = text.lower()                  # Lowercase
    text = re.sub(r"http\S+|www\S+", "", text)  # Xóa URL
    text = re.sub(r"@\w+", "", text)     # Xóa mention
    text = re.sub(r"\d{9,}", "", text)   # Xóa số điện thoại
    text = re.sub(r"[^\w\s!?]", " ", text)  # Giữ chữ + ! + ?
    text = re.sub(r"\s+", " ", text).strip() # Xóa space thừa
    return text

df_comments["comment_text"] = df_comments["comment_text"].apply(clean_text)
df_comments = df_comments[df_comments["comment_text"].str.split().str.len() >= 2]

print("Shape sau clean:", df_comments.shape)

Shape sau clean: (1156871, 8)

In [12]:
df_comments.to_csv("../data_merge/df_comments_clean.csv", index=False)
print("Xuất xong!")

Xuất xong!